#!/bin/bash

#SBATCH --mem=200g
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-task=1    # match to OMP_NUM_THREADS
#SBATCH --partition=gpuA100x8     # or one of: gpuA100x4 gpuA40x4 gpuA100x8 gpuMI100x8
#SBATCH --account=bbpj-delta-gpu #msoltaninia
#SBATCH --job-name=myjobtest
#SBATCH --time=00:10:00      # hh:mm:ss for the job
### GPU options ###
##SBATCH --gpus-per-node=1
##SBATCH --gpu-bind=none     # or closest
##SBATCH --mail-user=ms69@alfred.edu
##SBATCH --mail-type="BEGIN,END" See sbatch or srun man pages for more email options

module reset # drop modules and explicitly load the ones needed
             # (good job metadata and reproducibility)
             # $WORK and $SCRATCH are now set
module load anaconda3_gpu  # ... or any appropriate modules
module list  # job documentation and metadata
echo "job is starting on `hostname`"
source activate global_finder310
# pip install kahypar
# pip install scipy
# pip install pennylane-sparse
# conda install -c conda-forge cuquantum-python
# conda install -c "conda-forge/label/broken" cuquantum-python
# pip install pennylane-lightning[gpu]

# conda remove -c anaconda cudatoolkit -y
# conda clean --all
# conda install -c anaconda cudatoolkit
# pip install pennylane[torch,cirq,qiskit]
srun python3 builder_min_max.py
echo "done"
